# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-02 14:08
from __future__ import unicode_literals

from django.db import migrations
import photo.fields


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0002_auto_20180302_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=photo.fields.ThumbnailImageField(upload_to='photo/%Y/%m'),
        ),
    ]
