# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-08 03:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0004_auto_20180307_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
